#!/bin/bash
# Synapse 仓库迁移脚本

echo "🚀 Synapse 仓库迁移指南"
echo "========================"
echo ""
echo "✅ 已完成:"
echo "  - 创建了干净的 Synapse 仓库"
echo "  - 推送到 GitHub: https://github.com/Blurjp/Synapse-Clean"
echo "  - 不包含敏感信息"
echo "  - 完整的 Synapse 品牌"
echo ""
echo "📍 新仓库位置:"
echo "  https://github.com/Blurjp/Synapse-Clean"
echo ""
echo "⚠️  需要你手动操作:"
echo ""
echo "步骤 1: 删除旧的 Synapse 仓库"
echo "  1. 访问: https://github.com/Blurjp/Synapse/settings"
echo "  2. 滚动到页面底部 'Danger Zone'"
echo "  3. 点击 'Delete this repository'"
echo "  4. 输入仓库名称确认删除"
echo ""
echo "步骤 2: 重命名 Synapse-Clean 为 Synapse"
echo "  运行以下命令:"
echo "  gh repo rename Synapse --repo Blurjp/Synapse-Clean"
echo ""
echo "或者，如果你想保留 Synapse-Clean 名称:"
echo "  - 直接使用 https://github.com/Blurjp/Synapse-Clean"
echo ""
echo "📦 新仓库内容:"
echo "  ✅ Frontend (Next.js 14)"
echo "  ✅ Backend (FastAPI)"
echo "  ✅ Chrome Extension"
echo "  ✅ Documentation"
echo "  ✅ Clean Git History"
echo "  ✅ No Sensitive Data"
echo ""
echo "🎉 完成！"
